-- 코드를 입력하세요
SELECT PROD.PRODUCT_ID, PROD.PRODUCT_NAME, SUM(PROD.PRICE * ORD.AMOUNT) TOTAL_SALES
FROM FOOD_PRODUCT PROD JOIN FOOD_ORDER ORD ON PROD.PRODUCT_ID = ORD.PRODUCT_ID

WHERE PRODUCE_DATE LIKE "2022-05%"

GROUP BY PROD.PRODUCT_ID, PROD.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, PROD.PRODUCT_ID ASC