SELECT 
    FI.ID AS ID,
    FN.FISH_NAME AS FISH_NAME,
    FI.LENGTH AS LENGTH
FROM 
    FISH_INFO FI
JOIN 
    FISH_NAME_INFO FN
ON 
    FI.FISH_TYPE = FN.FISH_TYPE
    
WHERE 
    FI.LENGTH = (
        SELECT MAX(SUB.LENGTH)
        FROM FISH_INFO SUB
        WHERE SUB.FISH_TYPE = FI.FISH_TYPE
    )
ORDER BY
    FI.ID ASC